config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # READ ALL TASKS
  get "tasks", to: "tasks#index"



  #CREATE TASK
  post "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new", as: "task_new"

  # READ ONE TASK
  get "tasks/:id", to: "tasks#show", as: "task"

  # UPDATE TASK
  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  patch "tasks/:id", to: "tasks#update"

  # DELETE A TASK
  delete 'tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end
end

 private

def set_task
  @task = Task.find(params[:id])
end

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.input :title %>

  <%= f.input :details %>

  <%= f.input :completed, as: :boolean %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
  <h1>Update task</h1>

<%= render "form", task: @task %>

<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/tasks/index.html.erb
<div class="container-fluid">
  <h1>Tasks</h1>


    <div class="pt-2 pb-2">
      <% @tasks.each do |task| %>

        <input type="checkbox" name="completed">
        <label for="completed"><%= link_to task.title, task_path(task.id) %></label>

        <%= link_to task_path(task.id),
          method: :delete,
          data: { confirm: "Delete #{task.title}?" } do %>
          <i class="fa fa-trash-o text-danger" aria-hidden="true"></i>
          <% end %>
          <%= link_to task_edit_path(task) do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>
          <% end %>
        <br>


      <% end %>
    </div>


  <%= link_to task_new_path do %>
    <i class="fa fa-plus"></i> Add a new task
  <% end %>
</div>

app/views/tasks/new.html.erb
  <h1>New task</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>TASK DETAILS</h1>


  <div class="container pt-3">
  <h2><%= @task.title %></h2>
  <p class="well"><%= @task.details %></p>

  <% if @task.completed %>
    <i class="fa fa-check-square-o"></i> This task is completed
  <% else %>
    <i class="fa fa-square-o"></i> This task is not completed yet
  <% end %>
  <%= link_to tasks_path do %>
    <br>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>